#!/bin/bash
# Installation de Yunofav dans Yunohost
app=favlinks

# Retrieve arguments
domain=$1
path=$2

# Check domain/path availability
#sudo yunohost app checkurl $domain$path -a $app
#if [[ ! $? -eq 0 ]]; then
#    exit 1
#fi

# Check web path availability
#ynh_webpath_available $domain $path
# Register (book) web path
#ynh_webpath_register $app $domain $path

# Copy files to the right place with the right permissions
final_path=/var/www/$app
sudo mkdir -p $final_path
sudo cp -a ../sources/* $final_path
sudo chown -R www-data: $final_path

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$path@g"  ../conf/nginx.conf
sed -i "s@WWWPATH@$final_path@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# Reload nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app ssowatconf
